=head1 NAME

Promised::Mysqld - MySQL server wrapper for testing

=head1 SYNOPSIS

  use Promised::Mysqld;
  $mysqld = Promised::Mysqld->new;
  $mysqld->start->then (sub {
    ...;
    return $mysqld->stop;
  })->then (sub {
    warn "done";
  });

=head1 DESCRIPTION

XXX

=head1 METHODS

=over 4

XXX

=item $promise = $mysqld->start

Return a L<Promise>, which is resolved after the MySQL server is ready
to accept queries.  The promise is rejected if the server failed to
start.

=item $promise = $mysqld->stop

Returna L<Promise>, which is resolved after the MySQL server is
shutdown.

This method must be invoked after the C<start> method is invoked.  It
can be invoked even when the C<start>'s promise is rejected.

=back

=head1 DEPENDENCY

This module requires Perl 5.12 or later.

The module requires L<Promise>
<https://github.com/wakaba/perl-promise>, L<Promised::Command>
<https://github.com/wakaba/perl-promised-command>, L<Promised::File>
<https://github.com/wakaba/perl-promised-file>, and L<AnyEvent>.

=head1 AUTHOR

Wakaba <wakaba@uikawiki.org>.

=head1 LICENSE

Copyright 2015 Wakaba <wakaba@suikawiki.org>.

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut
